[general]
import = [
    #"~/.config/alacritty/themes/themes/dawnfox.toml"
    "~/.config/alacritty/themes/themes/duskfox.toml"
]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 12.0

[font.normal]
family = "IosevkaTerm NF"
